FROM mcr.microsoft.com/azureml/curated/acpt-pytorch-1.13-py38-cuda11.7-gpu:1

# https://github.com/microsoft/Swin-Transformer/blob/main/get_started.md
RUN pip install timm==0.4.12 opencv-python==4.4.0.46 termcolor==1.1.0 yacs==0.1.8
